package com.example.designsystem.theme

import androidx.compose.runtime.compositionLocalOf
import com.example.ratatouille.R

data class Icons(
    val icLogo: Int = R.drawable.slider22,
    val icLogoMedium: Int = R.drawable.ic_logo_medium,
    val icGlobe: Int = R.drawable.ic_globe,
    val icFacebook: Int = R.drawable.ic_facebook,
    val icGoogle: Int = R.drawable.ic_google,
    val icError: Int = R.drawable.ic_error,
    val icEyeVisible: Int = R.drawable.ic_eye_visible,
    val iconVerify: Int = R.drawable.ic_confirm_email,
    val icVerify: Int = R.drawable.ic_verify_email,
    val icBackArrow: Int = R.drawable.ic_arrow_back,
    val icIndividual: Int = R.drawable.ic_individual,
    val icSeller: Int = R.drawable.ic_seller,
    val icBuyer: Int = R.drawable.ic_buyer,
    val icCompany: Int = R.drawable.ic_entrepreneur,
    val icDown: Int = R.drawable.ic_down,
    val icNoEye: Int = R.drawable.ic_no_eye,
    val icArrowUpRight: Int = R.drawable.ic_arrow_up_right,
    val icBids: Int = R.drawable.ic_bids,
    val icHome: Int = R.drawable.ic_home,
    val icLiveAuctions: Int = R.drawable.ic_live_auctions,
    val icMoreVertical: Int = R.drawable.ic_more_vertical,
    val icNotifications: Int = R.drawable.ic_notidication,
    val icProfile: Int = R.drawable.ic_profile,
    val icWoman: Int = R.drawable.ic_woman,
    val icCube: Int = R.drawable.ic_cube,
    val icDollar: Int = R.drawable.ic_dollar,
    val icDarkMode: Int = R.drawable.ic_moon_bg,
    val icNoResult: Int = R.drawable.ic_no_result,
    val icSearch: Int = R.drawable.ic_search,
    val icCalendar: Int = R.drawable.ic_calendar,
    val icDropDown: Int = R.drawable.ic_drop_down,
    val icGender: Int = R.drawable.ic_gender,
    val icGenerate: Int = R.drawable.ic_generate,
    val icMail: Int = R.drawable.ic_mail,
    val icPhone: Int = R.drawable.ic_phone,
    val icUser: Int = R.drawable.ic_user,
    val icSun: Int = R.drawable.ic_sun,
    val icMoon: Int = R.drawable.ic_moon,
    val icBell: Int = R.drawable.ic_bell,
    val icCreditCard: Int = R.drawable.ic_credit_card,
    val icBin: Int = R.drawable.ic_bin,
    val icFaq: Int = R.drawable.ic_faq,
    val icLogOut: Int = R.drawable.ic_log_out,
    val icPrivacy: Int = R.drawable.ic_privacy,
    val icSecurity: Int = R.drawable.ic_security,
    val icGlobeSettings: Int = R.drawable.ic_globe_settings,
    val icRemoveAccount: Int = R.drawable.ic_remove_account,
    val icClose: Int = R.drawable.ic_close,
    val icBurger: Int = R.drawable.ic_burger,
    val icTransactions: Int = R.drawable.ic_transactions,
    val icSupport: Int = R.drawable.ic_support,
    val icBookmarks: Int = R.drawable.ic_bookmark,
    val icLeave: Int = R.drawable.ic_leave_auction,
    val icLock: Int = R.drawable.ic_lock,
    val icTrash: Int = R.drawable.ic_trash,
    val icCreateAuction: Int = R.drawable.ic_create_auction,
    val icCurrencyDollar: Int = R.drawable.ic_currency_dollar,
    val icCurrencyEuro: Int = R.drawable.ic_currency_dollar,
    val icCurrencyLari: Int = R.drawable.ic_currency_dollar,
    val icPlus: Int = R.drawable.ic_plus,
    val icSuccess: Int = R.drawable.ic_success,
    val icBookmark: Int = R.drawable.ic_bookmark,
    val icBookmarked: Int = R.drawable.ic_bookmarked,
    val icSort: Int = R.drawable.ic_sort,
)

val DarkIcons = Icons(
    icLogo = R.drawable.slider22,
    icDarkMode = R.drawable.ic_sun_with_back,
    icBurger = R.drawable.ic_buger_dark,
)

val LightIcons = Icons(
    icLogo = R.drawable.slider22,
    icDarkMode = R.drawable.ic_moon_bg,
    icBurger = R.drawable.ic_burger,
)

val LocalIcons = compositionLocalOf { Icons() }
