package com.example.designsystem.theme

import androidx.compose.runtime.compositionLocalOf
import androidx.compose.ui.graphics.Color

data class CustomColorsPalette(
    //General - Background
    val textColorPrimary: Color = Color.Unspecified,
    val activeTextColor: Color = Color.Unspecified,
    val textColorSecondary: Color = Color.Unspecified,
    val greenDark: Color = Color.Unspecified,
    val green: Color = Color.Unspecified,
    val borderGrey: Color = Color.Unspecified,
    val textColorMain: Color = Color.Unspecified,
    val textColorAdditional: Color = Color.Unspecified,
    val buttonTextMain: Color = Color.Unspecified,
    val bgColorMain: Color = Color.Unspecified,
    val buttonTextAdditional: Color = Color.Unspecified,
    val outlineInActive: Color = Color.Unspecified,
    val outlineActive: Color = Color.Unspecified,
    val errorColor: Color = Color.Unspecified,
    val bgGray: Color = Color.Unspecified,
    val disabledButtonColor: Color = Color.Unspecified,
    val headerGray: Color = Color.Unspecified,
    val mediumGray: Color = Color.Unspecified,
    val gray: Color = Color.Unspecified,
    val strokeGray: Color = Color.Unspecified,
    val grayMedium2: Color = Color.Unspecified,
    val greyBold: Color = Color.Unspecified,
    val womanColor: Color = Color.Unspecified,
    val gradientBlue: Color = Color.Unspecified,
    val gradientPink: Color = Color.Unspecified,
    val profileFieldBorder: Color = Color.Unspecified,
    val switchBgColor: Color = Color.Unspecified,
    val pink: Color = Color.Unspecified,
    val greyMedium: Color = Color.Unspecified,
    val greyBg: Color = Color.Unspecified,
    val borderGreyMedium: Color = Color.Unspecified,
    val greenLive: Color = Color.Unspecified,
    val yellowUpcoming: Color = Color.Unspecified,
    val canceled: Color = Color.Unspecified,
    val completed: Color = Color.Unspecified,
    val draft: Color = Color.Unspecified,
    val auctionBg: Color = Color.Unspecified,
    val auctionBgSecondary: Color = Color.Unspecified,
    val sellerAuctionBg: Color = Color.Unspecified,
)

val LightCustomColorsPalette = CustomColorsPalette(
    textColorPrimary = Color(0xFF1D69E4),
    activeTextColor = Color(0xFF1D69E4),
    textColorSecondary = Color(0xFF4189FF),
    greenDark = Color(0xFF019710),
    borderGrey = Color(0xFF808080),
    bgColorMain = Color(0xFFFFFFFF),
    textColorMain = Color(0xFF000000),
    textColorAdditional = Color(0xFF000000).copy(alpha = 0.7f),
    buttonTextMain = Color(0xFFFFFFFF),
    buttonTextAdditional = Color(0xFF000000),
    outlineActive = Color(0xFF1D69E4),
    outlineInActive = Color(0xFF838383),
    errorColor = Color(0xFFF06464),
    bgGray = Color(0xFFEDEDED),
    disabledButtonColor = Color(0xFF1D69E4).copy(alpha = 0.3f),
    headerGray = Color(0xFFD2D2D2),
    mediumGray = Color(0xFFCCCCCC),
    profileFieldBorder = Color(0xFFCCCCCC),
    gray = Color(0xFFFAFAFA),
    strokeGray = Color(0xFFE9E9E9),
    green = Color(0xFF50C878),
    grayMedium2 = Color(0xFFF1F1F1),
    greyBold = Color(0xFFE4E4E4),
    womanColor = Color(0xFFB79EB0),
    gradientBlue = Color(0xFF64B0F9),
    gradientPink = Color(0xFFB36EC4),
    switchBgColor = Color(0xFF242424),
    pink = Color(0xFFFEF7FF),
    greyMedium = Color(0xFFE6E6E6),
    greyBg = Color(0xFFF1F1F1),
    borderGreyMedium = Color(0xFFD0D0D0),
    greenLive = Color(0xFF3D8340),
    yellowUpcoming = Color(0xFFE29A3B),
    canceled = Color(0xFFFF6B6B),
    completed = Color(0xFF5C9AFF),
    draft = Color(0xFFFFFFFF),
    auctionBg = Color(0xFFE2E2E2),
    auctionBgSecondary = Color(0xFFE4E4E4),
    sellerAuctionBg = Color(0xFFDEDEDE),
)

val DarkCustomColorsPalette = CustomColorsPalette(
    textColorPrimary = Color(0xFF1D69E4),
    activeTextColor = Color(0xFFFFFFFF),
    textColorSecondary = Color(0xFF4189FF),
    greenDark = Color(0xFF019710),
    borderGrey = Color(0xFFFFFFFF),
    bgColorMain = Color(0xFF141414),
    textColorMain = Color(0xFFFFFFFF),
    textColorAdditional = Color(0xFFFFFFFF).copy(alpha = 0.7f),
    buttonTextMain = Color(0xFFFFFFFF),
    buttonTextAdditional = Color(0xFFFFFFFF),
    outlineActive = Color(0xFF1D69E4),
    outlineInActive = Color(0xFF8A8A8A),
    errorColor = Color(0xFFF06464),
    bgGray = Color(0xFF202021),
    disabledButtonColor = Color(0xFF1D69E4).copy(alpha = 0.3f),
    headerGray = Color(0xFFFFFFFF),
    mediumGray = Color(0xFFCCCCCC),
    profileFieldBorder = Color(0xFF292929),
    gray = Color(0xFF161616),
    strokeGray = Color(0xFF202021),
    green = Color(0xFF50C878),
    grayMedium2 = Color(0xFF1A1A1A),
    greyBold = Color(0xFF212121),
    womanColor = Color(0xFFB79EB0),
    gradientBlue = Color(0xFF64B0F9),
    gradientPink = Color(0xFFB36EC4),
    switchBgColor = Color(0xFF242424),
    pink = Color(0xFF181818),
    greyMedium = Color(0xFFE6E6E6),
    greyBg = Color(0xFFF1F1F1),
    borderGreyMedium = Color(0xFFD0D0D0),
    greenLive = Color(0xFF3D8340),
    yellowUpcoming = Color(0xFFE29A3B),
    canceled = Color(0xFFFF6B6B),
    completed = Color(0xFF5C9AFF),
    draft = Color(0xFFFFFFFF),
    auctionBg = Color(0xFF212121),
    auctionBgSecondary = Color(0xFF2D2C2C),
    sellerAuctionBg = Color(0xFF212121),
)

val LocalPalette = compositionLocalOf { CustomColorsPalette() }
